<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
    <?php echo $this->headTitle('Admin - FHC Admin Interface')->setSeparator(' - ')->setAutoEscape(false)?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')?>

    <!-- Le styles -->
    <?php echo $this->headLink()->prependStylesheet('//netdna.bootstrapcdn.com/twitter-bootstrap/2.1.1/css/bootstrap-combined.min.css')?>

    <!-- Scripts -->
    <?php
				
echo $this->headScript ()->prependFile ( '//netdna.bootstrapcdn.com/twitter-bootstrap/2.1.1/js/bootstrap.min.js' )->prependFile ( '//code.jquery.com/jquery.min.js' )->prependFile ( '//html5shiv.googlecode.com/svn/trunk/html5.js', 'text/javascript', array (
						'conditional' => 'lt IE 9' 
				) )?>

  </head>

<body>
	
	<div class="navbar navbar-inverse">
		<div class="navbar-inner">
			<div class="container-fluid">
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> 
					<span class="icon-bar"></span> 
					<span class="icon-bar"></span> 
					<span class="icon-bar"></span>
				</a> 
				<a class="brand" href="<?php echo $this->url('admin') ?>">TOA Admin</a>
				<div class="nav-collapse collapse">
					<a class="btn pull-right" href="<?php echo $this->url("home") ?>">Home</a>
					<ul class="nav">
		              <li><a href="<?php echo $this->url('home')?>">Home</a></li>
            		</ul>
          		</div>
				<!--/.nav-collapse -->
			</div>
		</div>
	</div>

	<div class="container-fluid">

      <div class="row-fluid">
		<div class="span2">
			<div class="well sidebar-nav">
				<?php echo $this->navigation ( 'admin_navigation' )
								->menu ()
								->setUlClass ( 'nav nav-list' )
								->setMaxDepth ( 1 );
				?>
			</div>
		</div>
		
		<div class="span10">
			<!--Body content-->
			<?php echo $this->content; ?>
		</div>
	</div>

      <hr>

		<footer>
			<p>&copy; 2012 水果硬糖(北京)网络科技有限公司   Fruit Hard Candy (Beijing) Network Technology Co., Ltd.</p>
		</footer>

	</div>
	<!-- /container -->

  <?php echo $this->inlineScript()?>
  </body>
</html>
