<div class="tabbable tabs-left">
	<ul class="nav nav-tabs" style="height: 300px;">
		<li><a href="<?php echo $this->url('payment');?>">充值信息</a></li>
		<li><a
			href="<?php echo $this->url('payment',array('action'=>'alipay'));?>">支付宝</a></li>
		<li><a
			href="<?php echo $this->url('payment',array('action'=>'yeepay'));?>">易宝支付</a></li>
	</ul>

	<div class="tab-content">
		<div class="page-header">
			<h2>充值信息介绍</h2>
		</div>
		
	</div>
</div>