<div class="tabbable tabs-left">
	<ul class="nav nav-tabs" style="height: 300px;">
		<li><a href="#paymentInfo" data-toggle="tab">充值信息</a></li>
		<li><a href="#alipay" data-toggle="tab">支付宝</a></li>
		<li class="active"><a href="#yeepay" data-toggle="tab">易宝支付</a></li>
	</ul>
	<div class="tab-content">
		<div class="tab-pane " id="paymentInfo">
			<div class="page-header">
				<h2>充值信息</h2>
			</div>
		</div>
		<div class="tab-pane" id="alipay">
			<div class="page-header">
				<h2>支付宝</h2>
			</div>
		</div>

		<div class="tab-pane active" id="yeepay">
			<div class="page-header">
				<h2>易宝支付</h2>
			</div>
			<div class="well">
				<p>选择充值方式</p>
				<div class="btn-group" data-toggle="buttons-radio">
					<button id="yeepayYH" class="btn active">银行</button>
					<button id="yeepayFYH" class="btn">Q币</button>
				</div>
				<label>优惠方案</label>
				<div id="yeepayYHYouhui" class="row">
					<div id="youhui01" class='btn youhui span2'>
						<label>充值6元以内</label> <label>现金打95折</label>
					</div>
					<div id="youhui02" class='btn youhui span2'>
						<label>充值12元以上</label> <label>现金打9折</label>
					</div>
				</div>
				<div id="yeepayFYHYouhui" class="row">
					<div id="youhui03" class='btn youhui span2'>
						<label>充值20Q币以内</label> <label>1Q币=7金币</label>
					</div>
					<div id="youhui04" class='btn youhui span2'>
						<label>充值50Q币以内</label> <label>1Q币=8金币</label>
					</div>
					<div id="youhui05" class='btn youhui span2'>
						<label>充值100Q币以上</label> <label>1Q币=9金币</label>
					</div>
				</div>
			</div>
			<div class="row well">
				<div class="span4">
				<form>
					<label>充值金额</label> <label>充值：<span id="total"></span>金币
					</label>
					<div class="input-prepend input-append">
						<span class="add-on">实付</span><input id="amount" type="text"
							class="span2" placeholder="请输入金额" /><span id="type"
							class="add-on"></span>
					</div>
					<button type="submit" class="btn">确认充值</button>
				</form>
				</div>
				<div class="alert alert-success span2">
					<strong>当前方案</strong>
					<div id="currentYH"></div>
				</div>
				<div class="alert span2">
					<strong>当然！</strong>
					您也可以手动输入自己想到购买的金额，我们将会用最优方式结算。
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$("#yeepayFYHYouhui").hide();
	$("#type").html("人民币");
  $("#yeepayYH").click(function(){
  	$("#yeepayYHYouhui").show();
  	$("#yeepayFYHYouhui").hide();
  	$("#type").html("人民币");
  });
  $("#yeepayFYH").click(function(){
	$("#yeepayYHYouhui").hide();
	$("#yeepayFYHYouhui").show();
	$("#type").html("Q币");
  });
  $("#youhui01").click(function(){
	  $("#amount").val(6*0.95);
	  $("#type").html("人民币");
	  $("#total").html(6*10);
	  $("#currentYH").html("6*0.95");
  })
  $("#youhui02").click(function(){
	  $("#amount").val(12*0.9);
	  $("#type").html("人民币");
	  $("#total").html(12*10);
	  $("#currentYH").html("12*0.9");
  })
  $("#youhui03").click(function(){
	  $("#amount").val(20);
	  $("#type").html("Q币");
	  $("#total").html(20*7);
	  $("#currentYH").html("20*7");
  })
  $("#youhui04").click(function(){
	  $("#amount").val(50);
	  $("#type").html("Q币");
	  $("#total").html(50*8);
	  $("#currentYH").html("50*8");
  })
  $("#youhui05").click(function(){
	  $("#amount").val(100);
	  $("#type").html("Q币");
	  $("#total").html(100*9);
	  $("#currentYH").html("100*9");
  })
});
</script>