<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination 
-->
<?php 
$url = $this->route;
?>

<?php if ($this->pageCount): ?>
<div class="pagination">
<ul>
<?php if (isset($this->previous)){ ?>
	<li>
<?php } else { ?>
	<li class="disabled">
<?php } ?>
	<a href="<?php echo $url. $this->previous; ?>">Prev</a>
</li>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
	<?php if ($page != $this->current) { ?>
		<li>
	<?php  } else { ?>
		<li class="active">
	<?php  } ?>
	    <a href="<?php echo $url. $page;?>"><?php echo $page; ?></a>
	</li>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)){ ?>
	<li>
<?php } else { ?>
	<li class="disabled">
<?php } ?>
	<a href="<?php echo $url. $this->next; ?>">Next</a>
</li>

</ul>
</div>
<?php endif; ?>