<div class='navbar'>
	<div class="navbar-inner">
		<a class="brand" href="/admin/promo">促销管理</a>
		<ul class='nav' id='promoTab'>
			<li><a href='/admin/promo'>列表</a></li>
			<li><a href='/admin/promo/add'>创建</a></li>
		</ul>
	</div>
</div>
<script>
	//主菜单动作
	$(function() {
		var url = window.location;
		// Will only work if string in href matches with location
		$('#promoTab a[href="' + url + '"]').parent().addClass('active');

		// Will also work for relative and absolute hrefs
		$('#promoTab a').filter(function() {
			return this.href == url;
		}).parent().addClass('active');
	})
</script>