<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
<?php echo $this->headTitle($this->translate('水果硬糖').$this->translate('(北京)网络科技有限公司'))->setSeparator(' - ')->setAutoEscape(false)?>

<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')?>

<!-- Le styles -->
<?php

echo $this->headLink ( array (
		'rel' => 'shortcut icon',
		'type' => 'image/vnd.microsoft.icon',
		'href' => $this->basePath () . '/images/favicon.ico' 
) )
->prependStylesheet ( $this->basePath () . '/css/bootstrap-responsive.min.css' )
->prependStylesheet ( $this->basePath () . '/css/bootstrap.min.css' )
->prependStylesheet ( $this->basePath () . '/css/font-awesome.min.css' )
->prependStylesheet ( $this->basePath () . '/css/style.css' )
?>

<!-- Scripts -->
<?php

echo $this->headScript ()
->prependFile ( $this->basePath () . '/js/html5.js', 'text/javascript', array (
		'conditional' => 'lt IE 9' 
) )
->prependFile ( $this->basePath () . '/js/application.js' )
->prependFile ( $this->basePath () . '/js/bootstrap-scrollspy.js' )
->prependFile ( $this->basePath () . '/js/bootstrap-tab.js' )
->prependFile ( $this->basePath () . '/js/bootstrap-button.js' )
->prependFile ( $this->basePath () . '/js/bootstrap.min.js' )
->prependFile ( $this->basePath () . '/js/jquery.min.js' )
?>
	
</head>
<body data-spy="scroll" data-target=".subnav" data-offset="50">
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">

				<a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('水果硬糖') ?></a>

				<a class="btn btn-navbar" data-toggle="collapse"
					data-target=".nav-collapse"> <span class="icon-bar"></span> <span
					class="icon-bar"></span> <span class="icon-bar"></span>
				</a>
				
				<?php IF ($this->userIdentity ()) { ?>
				<!-- user dropdown starts -->
				<div class="btn-group pull-right">
					<a class="btn btn-inverse btn-login dropdown-toggle" data-toggle="dropdown" href="#"> <i
						class="icon-user"></i><span class="hidden-phone"> <?php echo $this->userDisplayName ();?></span>
						<span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
						<li><a href="/user">Profile</a></li>
						<li class="divider"></li>
						<li><a href="/user/logout">Logout</a></li>
					</ul>
				</div>
				<!-- user dropdown ends -->
				<?php } else { ?>
					<div class="btn pull-right">
						<a href="/user/login">登录</a>
					</div>
				<?php }?>
				
				<div class="nav-collapse collapse">
					<ul class="nav">
						<li><a href="<?php echo $this->url('home') ?>">首页</a></li>
						<li><a href="<?php echo $this->url('info') ?>">游戏介绍</a></li>
						<li><a href="<?php echo $this->url('payment')?>">充值</a></li>
						<li><a href="<?php echo $this->url('admin')?>">后台</a></li>
					</ul>
				</div>
				<!--/.nav-collapse -->

			</div>
		</div>
	</div>

	<div class="container">
		<?php echo $this->content; ?>
		<hr>
		<footer>
			<p>
				&copy; 2012 水果硬糖(北京)网络科技有限公司   Fruit Hard Candy (Beijing) Network Technology Co., Ltd.
			</p>
		</footer>
	</div>
	
	
	
	<!-- /container -->
	<?php echo $this->inlineScript()?>
	
</body>
</html>
