<?php
$action = $this->form->get ( 'action' )->getValue ();
?>

<div class="container">
	<div class='navbar'>
		<div class="navbar-inner">
			<a class="brand" href="/admin/promo">促销管理</a>
			<ul class='nav'>
				<li><a href='/admin/promo/add'>创建</a></li>
			</ul>
		</div>
	</div>

	<div class="tab-content">
		<div class="tab-pane active" id="list">列表</div>
		<div class="tab-pane" id="add">
<?php
$form = $this->form;
$form->prepare ();
$form->setAttribute ( 'action', $this->url ( 'adminPromo' ) );
$form->setAttribute ( 'method', 'post' );
$form->get ( 'action' )->setValue ( 'add' );

$form->setAttribute ( 'class', 'form-horizontal' );
$form->get ( 'submit' )->setAttribute ( 'class', 'btn' )->setValue ( '提交' );

echo $this->form ()->openTag ( $form );
echo $this->formHidden ( $form->get ( 'id' ) );
echo $this->formHidden ( $form->get ( 'action' ) );
?>
<div class='control-group'>
				<label class="control-label" for="inputText">名称</label>
				<div class='controls'>
	<?php echo $this->formRow ( $form->get ( 'name' ) ); ?>
	</div>
			</div>
			<div class='control-group'>
				<label class="control-label" for="inputText">说明</label>
				<div class='controls'>
	<?php echo $this->formRow ( $form->get ( 'desc' ) ); ?>
	</div>
			</div>
			<div class='control-group'>
				<label class="control-label" for="inputText">充值接口</label>
				<div class='controls'>
	<?php echo $this->formRow ( $form->get ( 'adapter' ) ); ?>
	</div>
			</div>
			<div class='control-group'>
				<label class="control-label" for="inputText">充值货币</label>
				<div class='controls'>
	<?php echo $this->formRow ( $form->get ( 'currency' ) ); ?>
	</div>
			</div>
			<div class='control-group'>
				<label class="control-label" for="inputText">每单位转换金币</label>
				<div class='controls'>
	<?php echo $this->formRow ( $form->get ( 'gold' ) ); ?>
	</div>
			</div>
			<div class='control-group'>
				<label class="control-label" for="inputText">货币打折率</label>
				<div class='controls'>
	<?php echo $this->formRow ( $form->get ( 'off' ) ); ?>
	</div>
			</div>
			<div class='control-group'>
				<div class='controls'>
	<?php echo $this->formSubmit ( $form->get ( 'submit' ) ); ?>
	</div>
			</div>

<?php echo $this->form()->closeTag()?>
  </div>
	</div>

</div>

<script type="text/javascript">
<!--
	$('#promoTab a[href=#<?php echo $action;?>]').tab('show');
//-->
</script>