<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'WhBase\Module'                                    => __DIR__ . '/Module.php',
    'WhBase\Form\ProvidesEventsForm'                   => __DIR__ . '/src/Form/ProvidesEventsForm.php',
    'WhBase\Mapper\Exception\ExceptionInterface'       => __DIR__ . '/src/Mapper/Exception/ExceptionInterface.php',
    'WhBase\Mapper\Exception\InvalidArgumentException' => __DIR__ . '/src/Mapper/Exception/InvalidArgumentException.php',
    'WhBase\Mapper\AbstractDbMapper'                   => __DIR__ . '/src/Mapper/AbstractDbMapper.php',
    'WhBase\EventManager\EventProvider'                => __DIR__ . '/src/EventManager/EventProvider.php',
    'WhBase\Module\AbstractModule'                     => __DIR__ . '/src/Module/AbstractModule.php',
);