<div class='hero-unit'>
	“黎明黑夜”简称“黎明”。由水果硬糖推出的休闲类网络游戏。以互动娱乐为主体。为玩家无聊的零碎时间提供高品质的互动娱乐游戏为宗旨。“黎明”为玩家提供多种模式的娱乐方式。单人任务，多人联网互动等等，并且在游戏中提供多种娱乐方式。强大而丰富的道具种类。简单直观的操作方式。并且融入实时天气系统对游戏的影响，更大的丰富了游戏的多样性和用户体验。还在等待什么，赶快加入吧。我们等待着您的光临。
</div>
<div class='row-fluid'>

	<div class='well span3 index-height'>
		<div>
			<h5>
				<i class='icon-user'></i>在线客服
			</h5>
		</div>
		<div>
			<p>如果您在游戏过程中遇到任何问题，请立即与我们的客服专员取得联系。</p>
		</div>
		<div class='btn btn-warning pull-right'>提交客服问题</div>
	</div>

	<div class='well span5 index-height'>
		<div>
			<h5>
				<i class='icon-download-alt'></i>游戏下载
			</h5>
		</div>
		<div>
			<h1>
				<a href="#">点击下载</a>
			</h1>
		</div>
		<div class='btn btn-warning pull-right'>提交客服问题</div>
	</div>

	<div class='well span4 pull-right index-height'>
		<div>
			<h5>
				<i class='icon-download-alt'></i>最新信息
			</h5>
		</div>
		<div>如果您在游戏过程中遇到任何问题，请立即与我们的客服专员取得联系。请立即与我们的客服专员取得联系。</div>
		<div class='btn btn-warning pull-right'>查看</div>
	</div>
</div>